# https://aka.ms/yaml

variables:
- name: $(Test.TestCaseAccessToken)

trigger:
- master
 
jobs:
- job: RunTest1
  displayName: 'Run Tests'
  pool: Default
  steps:              
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'latestPreRelease'

  - task: ScreenResolutionUtility@1
    inputs:
      displaySettings: 'optimal'
 
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**/*.dll'
      uiTests: true
      searchFolder: '$(System.DefaultWorkingDirectory)\DSDrivenCodedUITest\bin\Debug\'
      vsTestVersion: latest

  

